wandb_version: 1

lr:
  desc: null
  value: 0.0005
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0001
patience:
  desc: null
  value: 3
threshold_mode:
  desc: null
  value: rel
factor:
  desc: null
  value: 0.7
verbose:
  desc: null
  value: true
loss_function:
  desc: null
  value: CrossEntropyLoss
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 256
data_dir:
  desc: null
  value: /home/ljc/aq/hw2/p2/11-785-f24-hw2p2-verification/cls_data
data_ver_dir:
  desc: null
  value: /home/ljc/aq/hw2/p2/11-785-f24-hw2p2-verification/ver_data
checkpoint_dir:
  desc: null
  value: /home/ljc/aq/hw2/p2/11-785-f24-hw2p2-verification
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.39.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1729427808.0735
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.8
      5: 0.16.1
      6: 4.39.1
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
